# Generated by Django 5.1.6 on 2025-02-22 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_created_at_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.team'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teammembers',
            unique_together={('user', 'team')},
        ),
    ]
