# Generated by Django 5.1.6 on 2025-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_teammembers_team_alter_teammembers_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='team',
        ),
        migrations.AddField(
            model_name='projects',
            name='team',
            field=models.ManyToManyField(to='api.team'),
        ),
    ]
