# Generated by Django 5.1.6 on 2025-02-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_projects_team_projects_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='status',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='team',
        ),
        migrations.CreateModel(
            name='ProjectTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('On Going', 'On Going'), ('completed', 'Completed')], default='On Going', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'unique_together': {('project', 'team')},
            },
        ),
    ]
