# Generated by Django 5.1.6 on 2025-02-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_projects_status_remove_projects_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteams',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-22 12:44:07.093271+05:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectteams',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
