# Generated by Django 5.1.6 on 2025-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_projectteams_created_at_projectteams_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteams',
            name='status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Completed', 'Completed')], default='On Going', max_length=20),
        ),
    ]
