# Generated by Django 5.1.6 on 2025-02-27 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_projectcomments_delete_taskcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('team', 'Added to a Team'), ('project', 'Added to a Project'), ('task', 'Assigned a Task'), ('comment', 'Project Comment')], default='team', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
