# Generated by Django 5.1.6 on 2025-02-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('team', 'Added to a Team'), ('project', 'Added to a Project'), ('task', 'Assigned a Task'), ('comment', 'Project Comment'), ('delete', 'Removed from a Team')], max_length=20),
        ),
    ]
